# Lesson 1.7 - Intro to NumPy

**Topics**
- Creating arrays
- Multi-dimensional arrays
- Randomly generated arrays
- Element-wise operations
  - Comparison operations
  - Logical operations
- Summarizing operations

## Import NumPy

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/red/ml-zoomcamp-2026/.venv/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
# Create a numpy array filled with a specific value
np.full(5, 12)

array([12, 12, 12, 12, 12])

In [7]:
# Create a numpy array from a list
my_list = [1, 2, 3, 4, 5]
print(my_list)
print(type(my_list))

print("")

np_array = np.array(my_list)
print(np_array)
print(type(np_array))

[1, 2, 3, 4, 5]
<class 'list'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
# Accessing elements in a NumPy array
print(np_array[0])
print(np_array[2])
print(np_array[-1])

1
3
5


In [9]:
# Changing values in a NumPy array
np_array[0] = 10
print(np_array)

[10  2  3  4  5]


In [10]:
# Generate a range of numbers
print(np.arange(10)) # Generate numbers from 0 to 9
print(np.arange(5, 15)) # Generate numbers from 5 to 14
print(np.arange(0, 20, 2)) # Generate even numbers from 0 to 18

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
np.linspace(0, 1, 5) # Generate 5 evenly spaced numbers between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Multi-dimensional arrays

In [12]:
# Generate a matrix of zeros with 5 rows and 2 columns
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
# Create a numpy array from a list of lists (2D array)
list_of_lists = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix = np.array(list_of_lists)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# Accessing elements in a NumPy array
print(matrix[0, 0])  # Access the element in the first row and first column
print(matrix[1, 2])  # Access the element in the second row and third column
print(matrix[2, 1])  # Access the element in the third row and second column
print(matrix[2, 2])  # Access the element in the third row and third column

1
6
8
9


In [15]:
# Changing elements in a 2D NumPy array
matrix[1, 2] = 99  # Change the element in the second row and third column to 99

print(matrix)

[[ 1  2  3]
 [ 4  5 99]
 [ 7  8  9]]


In [16]:
# Access only rows
print(matrix[0])  # Access the first row

[1 2 3]


In [17]:
# Change an entire row
matrix[0] = [10, 20, 30]  # Change the first row

print(matrix)

[[10 20 30]
 [ 4  5 99]
 [ 7  8  9]]


In [18]:
# Acess only columns
print(matrix[:, 1])  # Access the second column

[20  5  8]


In [19]:
# Replace an entire column
matrix[:, 1] = [100, 200, 300] # Change the second column

print(matrix)

[[ 10 100  30]
 [  4 200  99]
 [  7 300   9]]


## Randomly generated arrays

In [20]:
# Generate a 5x2 array of random numbers between 0 and 1 (uses the uniform distribution)
np.random.rand(5, 2)

array([[0.87886525, 0.04143101],
       [0.75590859, 0.75038226],
       [0.50774659, 0.25284515],
       [0.68458786, 0.41613613],
       [0.63589631, 0.05663265]])

In [21]:
# Set the random seed for reproducibility
np.random.seed(42)

# Generate a 5x2 array of random numbers between 0 and 1 (always the same due to the seed)
np.random.rand(5, 2) 

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [22]:
# Generate random numbers from a normal distribution (mean=0, std=1)
np.random.randn(5, 2)

array([[-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024],
       [-1.72491783, -0.56228753],
       [-1.01283112,  0.31424733]])

In [23]:
# Generate random integers
np.random.randint(0, 10, size=(5, 2))

array([[2, 6],
       [3, 8],
       [2, 4],
       [2, 6],
       [4, 8]])

## Element-wise operations

In [27]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [29]:
# You can directly perform operations on NumPy arrays
arr + 1

array([1, 2, 3, 4, 5])

In [ ]:
# Avoids the need for loops and makes the code more efficient
arr * 2

array([0, 2, 4, 6, 8])

In [33]:
# More complex operations
# Key is to remember that this formula applies to each element in the array
arr2 = (10 + (arr * 2)) ** 2
arr2

array([100, 144, 196, 256, 324])

In [34]:
# You can even perform operations between two arrays of the same shape
arr3 = arr + arr2
arr3

array([100, 145, 198, 259, 328])

## Comparison operations

In [36]:
a = np.arange(5)
print(a)

# Returns a boolean array (True if the element is even, False if it is odd)
a % 2 == 0

[0 1 2 3 4]


array([ True, False,  True, False,  True])

In [38]:
# Boolean indexing: select only the even numbers from the array
a[a % 2 == 0]

array([0, 2, 4])

## Summarizing operations (aggregations)

In [40]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(10)

In [45]:
arr.sum()

np.int64(55)

In [44]:
arr.mean()

np.float64(5.5)

In [46]:
arr.std()

np.float64(2.8722813232690143)